// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: commands.proto

package club.moddedminecraft.polychat.core.messagelibrary;

public final class CommandProtos {
  private CommandProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GenericCommandOrBuilder extends
      // @@protoc_insertion_point(interface_extends:polychat.GenericCommand)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string discordChannelId = 1;</code>
     */
    java.lang.String getDiscordChannelId();
    /**
     * <code>optional string discordChannelId = 1;</code>
     */
    com.google.protobuf.ByteString
        getDiscordChannelIdBytes();

    /**
     * <code>optional string discordCommandName = 2;</code>
     */
    java.lang.String getDiscordCommandName();
    /**
     * <code>optional string discordCommandName = 2;</code>
     */
    com.google.protobuf.ByteString
        getDiscordCommandNameBytes();

    /**
     * <code>optional string defaultCommand = 3;</code>
     */
    java.lang.String getDefaultCommand();
    /**
     * <code>optional string defaultCommand = 3;</code>
     */
    com.google.protobuf.ByteString
        getDefaultCommandBytes();

    /**
     * <code>optional string args = 4;</code>
     */
    java.lang.String getArgs();
    /**
     * <code>optional string args = 4;</code>
     */
    com.google.protobuf.ByteString
        getArgsBytes();
  }
  /**
   * Protobuf type {@code polychat.GenericCommand}
   */
  public  static final class GenericCommand extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:polychat.GenericCommand)
      GenericCommandOrBuilder {
    // Use GenericCommand.newBuilder() to construct.
    private GenericCommand(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GenericCommand() {
      discordChannelId_ = "";
      discordCommandName_ = "";
      defaultCommand_ = "";
      args_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private GenericCommand(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              discordChannelId_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              discordCommandName_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              defaultCommand_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              args_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return club.moddedminecraft.polychat.core.messagelibrary.CommandProtos.internal_static_polychat_GenericCommand_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return club.moddedminecraft.polychat.core.messagelibrary.CommandProtos.internal_static_polychat_GenericCommand_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              club.moddedminecraft.polychat.core.messagelibrary.CommandProtos.GenericCommand.class, club.moddedminecraft.polychat.core.messagelibrary.CommandProtos.GenericCommand.Builder.class);
    }

    public static final int DISCORDCHANNELID_FIELD_NUMBER = 1;
    private volatile java.lang.Object discordChannelId_;
    /**
     * <code>optional string discordChannelId = 1;</code>
     */
    public java.lang.String getDiscordChannelId() {
      java.lang.Object ref = discordChannelId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        discordChannelId_ = s;
        return s;
      }
    }
    /**
     * <code>optional string discordChannelId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getDiscordChannelIdBytes() {
      java.lang.Object ref = discordChannelId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        discordChannelId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DISCORDCOMMANDNAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object discordCommandName_;
    /**
     * <code>optional string discordCommandName = 2;</code>
     */
    public java.lang.String getDiscordCommandName() {
      java.lang.Object ref = discordCommandName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        discordCommandName_ = s;
        return s;
      }
    }
    /**
     * <code>optional string discordCommandName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDiscordCommandNameBytes() {
      java.lang.Object ref = discordCommandName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        discordCommandName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DEFAULTCOMMAND_FIELD_NUMBER = 3;
    private volatile java.lang.Object defaultCommand_;
    /**
     * <code>optional string defaultCommand = 3;</code>
     */
    public java.lang.String getDefaultCommand() {
      java.lang.Object ref = defaultCommand_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        defaultCommand_ = s;
        return s;
      }
    }
    /**
     * <code>optional string defaultCommand = 3;</code>
     */
    public com.google.protobuf.ByteString
        getDefaultCommandBytes() {
      java.lang.Object ref = defaultCommand_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        defaultCommand_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ARGS_FIELD_NUMBER = 4;
    private volatile java.lang.Object args_;
    /**
     * <code>optional string args = 4;</code>
     */
    public java.lang.String getArgs() {
      java.lang.Object ref = args_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        args_ = s;
        return s;
      }
    }
    /**
     * <code>optional string args = 4;</code>
     */
    public com.google.protobuf.ByteString
        getArgsBytes() {
      java.lang.Object ref = args_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        args_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getDiscordChannelIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, discordChannelId_);
      }
      if (!getDiscordCommandNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, discordCommandName_);
      }
      if (!getDefaultCommandBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, defaultCommand_);
      }
      if (!getArgsBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, args_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getDiscordChannelIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, discordChannelId_);
      }
      if (!getDiscordCommandNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, discordCommandName_);
      }
      if (!getDefaultCommandBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, defaultCommand_);
      }
      if (!getArgsBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, args_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof club.moddedminecraft.polychat.core.messagelibrary.CommandProtos.GenericCommand)) {
        return super.equals(obj);
      }
      club.moddedminecraft.polychat.core.messagelibrary.CommandProtos.GenericCommand other = (club.moddedminecraft.polychat.core.messagelibrary.CommandProtos.GenericCommand) obj;

      boolean result = true;
      result = result && getDiscordChannelId()
          .equals(other.getDiscordChannelId());
      result = result && getDiscordCommandName()
          .equals(other.getDiscordCommandName());
      result = result && getDefaultCommand()
          .equals(other.getDefaultCommand());
      result = result && getArgs()
          .equals(other.getArgs());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + DISCORDCHANNELID_FIELD_NUMBER;
      hash = (53 * hash) + getDiscordChannelId().hashCode();
      hash = (37 * hash) + DISCORDCOMMANDNAME_FIELD_NUMBER;
      hash = (53 * hash) + getDiscordCommandName().hashCode();
      hash = (37 * hash) + DEFAULTCOMMAND_FIELD_NUMBER;
      hash = (53 * hash) + getDefaultCommand().hashCode();
      hash = (37 * hash) + ARGS_FIELD_NUMBER;
      hash = (53 * hash) + getArgs().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static club.moddedminecraft.polychat.core.messagelibrary.CommandProtos.GenericCommand parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static club.moddedminecraft.polychat.core.messagelibrary.CommandProtos.GenericCommand parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static club.moddedminecraft.polychat.core.messagelibrary.CommandProtos.GenericCommand parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static club.moddedminecraft.polychat.core.messagelibrary.CommandProtos.GenericCommand parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static club.moddedminecraft.polychat.core.messagelibrary.CommandProtos.GenericCommand parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static club.moddedminecraft.polychat.core.messagelibrary.CommandProtos.GenericCommand parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static club.moddedminecraft.polychat.core.messagelibrary.CommandProtos.GenericCommand parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static club.moddedminecraft.polychat.core.messagelibrary.CommandProtos.GenericCommand parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static club.moddedminecraft.polychat.core.messagelibrary.CommandProtos.GenericCommand parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static club.moddedminecraft.polychat.core.messagelibrary.CommandProtos.GenericCommand parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(club.moddedminecraft.polychat.core.messagelibrary.CommandProtos.GenericCommand prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code polychat.GenericCommand}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:polychat.GenericCommand)
        club.moddedminecraft.polychat.core.messagelibrary.CommandProtos.GenericCommandOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return club.moddedminecraft.polychat.core.messagelibrary.CommandProtos.internal_static_polychat_GenericCommand_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return club.moddedminecraft.polychat.core.messagelibrary.CommandProtos.internal_static_polychat_GenericCommand_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                club.moddedminecraft.polychat.core.messagelibrary.CommandProtos.GenericCommand.class, club.moddedminecraft.polychat.core.messagelibrary.CommandProtos.GenericCommand.Builder.class);
      }

      // Construct using club.moddedminecraft.polychat.core.messagelibrary.CommandProtos.GenericCommand.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        discordChannelId_ = "";

        discordCommandName_ = "";

        defaultCommand_ = "";

        args_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return club.moddedminecraft.polychat.core.messagelibrary.CommandProtos.internal_static_polychat_GenericCommand_descriptor;
      }

      public club.moddedminecraft.polychat.core.messagelibrary.CommandProtos.GenericCommand getDefaultInstanceForType() {
        return club.moddedminecraft.polychat.core.messagelibrary.CommandProtos.GenericCommand.getDefaultInstance();
      }

      public club.moddedminecraft.polychat.core.messagelibrary.CommandProtos.GenericCommand build() {
        club.moddedminecraft.polychat.core.messagelibrary.CommandProtos.GenericCommand result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public club.moddedminecraft.polychat.core.messagelibrary.CommandProtos.GenericCommand buildPartial() {
        club.moddedminecraft.polychat.core.messagelibrary.CommandProtos.GenericCommand result = new club.moddedminecraft.polychat.core.messagelibrary.CommandProtos.GenericCommand(this);
        result.discordChannelId_ = discordChannelId_;
        result.discordCommandName_ = discordCommandName_;
        result.defaultCommand_ = defaultCommand_;
        result.args_ = args_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof club.moddedminecraft.polychat.core.messagelibrary.CommandProtos.GenericCommand) {
          return mergeFrom((club.moddedminecraft.polychat.core.messagelibrary.CommandProtos.GenericCommand)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(club.moddedminecraft.polychat.core.messagelibrary.CommandProtos.GenericCommand other) {
        if (other == club.moddedminecraft.polychat.core.messagelibrary.CommandProtos.GenericCommand.getDefaultInstance()) return this;
        if (!other.getDiscordChannelId().isEmpty()) {
          discordChannelId_ = other.discordChannelId_;
          onChanged();
        }
        if (!other.getDiscordCommandName().isEmpty()) {
          discordCommandName_ = other.discordCommandName_;
          onChanged();
        }
        if (!other.getDefaultCommand().isEmpty()) {
          defaultCommand_ = other.defaultCommand_;
          onChanged();
        }
        if (!other.getArgs().isEmpty()) {
          args_ = other.args_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        club.moddedminecraft.polychat.core.messagelibrary.CommandProtos.GenericCommand parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (club.moddedminecraft.polychat.core.messagelibrary.CommandProtos.GenericCommand) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object discordChannelId_ = "";
      /**
       * <code>optional string discordChannelId = 1;</code>
       */
      public java.lang.String getDiscordChannelId() {
        java.lang.Object ref = discordChannelId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          discordChannelId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string discordChannelId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getDiscordChannelIdBytes() {
        java.lang.Object ref = discordChannelId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          discordChannelId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string discordChannelId = 1;</code>
       */
      public Builder setDiscordChannelId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        discordChannelId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string discordChannelId = 1;</code>
       */
      public Builder clearDiscordChannelId() {
        
        discordChannelId_ = getDefaultInstance().getDiscordChannelId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string discordChannelId = 1;</code>
       */
      public Builder setDiscordChannelIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        discordChannelId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object discordCommandName_ = "";
      /**
       * <code>optional string discordCommandName = 2;</code>
       */
      public java.lang.String getDiscordCommandName() {
        java.lang.Object ref = discordCommandName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          discordCommandName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string discordCommandName = 2;</code>
       */
      public com.google.protobuf.ByteString
          getDiscordCommandNameBytes() {
        java.lang.Object ref = discordCommandName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          discordCommandName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string discordCommandName = 2;</code>
       */
      public Builder setDiscordCommandName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        discordCommandName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string discordCommandName = 2;</code>
       */
      public Builder clearDiscordCommandName() {
        
        discordCommandName_ = getDefaultInstance().getDiscordCommandName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string discordCommandName = 2;</code>
       */
      public Builder setDiscordCommandNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        discordCommandName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object defaultCommand_ = "";
      /**
       * <code>optional string defaultCommand = 3;</code>
       */
      public java.lang.String getDefaultCommand() {
        java.lang.Object ref = defaultCommand_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          defaultCommand_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string defaultCommand = 3;</code>
       */
      public com.google.protobuf.ByteString
          getDefaultCommandBytes() {
        java.lang.Object ref = defaultCommand_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          defaultCommand_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string defaultCommand = 3;</code>
       */
      public Builder setDefaultCommand(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        defaultCommand_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string defaultCommand = 3;</code>
       */
      public Builder clearDefaultCommand() {
        
        defaultCommand_ = getDefaultInstance().getDefaultCommand();
        onChanged();
        return this;
      }
      /**
       * <code>optional string defaultCommand = 3;</code>
       */
      public Builder setDefaultCommandBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        defaultCommand_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object args_ = "";
      /**
       * <code>optional string args = 4;</code>
       */
      public java.lang.String getArgs() {
        java.lang.Object ref = args_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          args_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string args = 4;</code>
       */
      public com.google.protobuf.ByteString
          getArgsBytes() {
        java.lang.Object ref = args_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          args_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string args = 4;</code>
       */
      public Builder setArgs(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        args_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string args = 4;</code>
       */
      public Builder clearArgs() {
        
        args_ = getDefaultInstance().getArgs();
        onChanged();
        return this;
      }
      /**
       * <code>optional string args = 4;</code>
       */
      public Builder setArgsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        args_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:polychat.GenericCommand)
    }

    // @@protoc_insertion_point(class_scope:polychat.GenericCommand)
    private static final club.moddedminecraft.polychat.core.messagelibrary.CommandProtos.GenericCommand DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new club.moddedminecraft.polychat.core.messagelibrary.CommandProtos.GenericCommand();
    }

    public static club.moddedminecraft.polychat.core.messagelibrary.CommandProtos.GenericCommand getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GenericCommand>
        PARSER = new com.google.protobuf.AbstractParser<GenericCommand>() {
      public GenericCommand parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new GenericCommand(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GenericCommand> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GenericCommand> getParserForType() {
      return PARSER;
    }

    public club.moddedminecraft.polychat.core.messagelibrary.CommandProtos.GenericCommand getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GenericCommandResultOrBuilder extends
      // @@protoc_insertion_point(interface_extends:polychat.GenericCommandResult)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string serverId = 1;</code>
     */
    java.lang.String getServerId();
    /**
     * <code>optional string serverId = 1;</code>
     */
    com.google.protobuf.ByteString
        getServerIdBytes();

    /**
     * <code>optional string discordChannelId = 2;</code>
     */
    java.lang.String getDiscordChannelId();
    /**
     * <code>optional string discordChannelId = 2;</code>
     */
    com.google.protobuf.ByteString
        getDiscordChannelIdBytes();

    /**
     * <code>optional string command = 3;</code>
     */
    java.lang.String getCommand();
    /**
     * <code>optional string command = 3;</code>
     */
    com.google.protobuf.ByteString
        getCommandBytes();

    /**
     * <code>optional string commandOutput = 4;</code>
     */
    java.lang.String getCommandOutput();
    /**
     * <code>optional string commandOutput = 4;</code>
     */
    com.google.protobuf.ByteString
        getCommandOutputBytes();

    /**
     * <code>optional string colour = 5;</code>
     */
    java.lang.String getColour();
    /**
     * <code>optional string colour = 5;</code>
     */
    com.google.protobuf.ByteString
        getColourBytes();
  }
  /**
   * Protobuf type {@code polychat.GenericCommandResult}
   */
  public  static final class GenericCommandResult extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:polychat.GenericCommandResult)
      GenericCommandResultOrBuilder {
    // Use GenericCommandResult.newBuilder() to construct.
    private GenericCommandResult(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GenericCommandResult() {
      serverId_ = "";
      discordChannelId_ = "";
      command_ = "";
      commandOutput_ = "";
      colour_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private GenericCommandResult(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              serverId_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              discordChannelId_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              command_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              commandOutput_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              colour_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return club.moddedminecraft.polychat.core.messagelibrary.CommandProtos.internal_static_polychat_GenericCommandResult_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return club.moddedminecraft.polychat.core.messagelibrary.CommandProtos.internal_static_polychat_GenericCommandResult_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              club.moddedminecraft.polychat.core.messagelibrary.CommandProtos.GenericCommandResult.class, club.moddedminecraft.polychat.core.messagelibrary.CommandProtos.GenericCommandResult.Builder.class);
    }

    public static final int SERVERID_FIELD_NUMBER = 1;
    private volatile java.lang.Object serverId_;
    /**
     * <code>optional string serverId = 1;</code>
     */
    public java.lang.String getServerId() {
      java.lang.Object ref = serverId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        serverId_ = s;
        return s;
      }
    }
    /**
     * <code>optional string serverId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getServerIdBytes() {
      java.lang.Object ref = serverId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        serverId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DISCORDCHANNELID_FIELD_NUMBER = 2;
    private volatile java.lang.Object discordChannelId_;
    /**
     * <code>optional string discordChannelId = 2;</code>
     */
    public java.lang.String getDiscordChannelId() {
      java.lang.Object ref = discordChannelId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        discordChannelId_ = s;
        return s;
      }
    }
    /**
     * <code>optional string discordChannelId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDiscordChannelIdBytes() {
      java.lang.Object ref = discordChannelId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        discordChannelId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COMMAND_FIELD_NUMBER = 3;
    private volatile java.lang.Object command_;
    /**
     * <code>optional string command = 3;</code>
     */
    public java.lang.String getCommand() {
      java.lang.Object ref = command_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        command_ = s;
        return s;
      }
    }
    /**
     * <code>optional string command = 3;</code>
     */
    public com.google.protobuf.ByteString
        getCommandBytes() {
      java.lang.Object ref = command_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        command_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COMMANDOUTPUT_FIELD_NUMBER = 4;
    private volatile java.lang.Object commandOutput_;
    /**
     * <code>optional string commandOutput = 4;</code>
     */
    public java.lang.String getCommandOutput() {
      java.lang.Object ref = commandOutput_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        commandOutput_ = s;
        return s;
      }
    }
    /**
     * <code>optional string commandOutput = 4;</code>
     */
    public com.google.protobuf.ByteString
        getCommandOutputBytes() {
      java.lang.Object ref = commandOutput_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        commandOutput_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COLOUR_FIELD_NUMBER = 5;
    private volatile java.lang.Object colour_;
    /**
     * <code>optional string colour = 5;</code>
     */
    public java.lang.String getColour() {
      java.lang.Object ref = colour_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        colour_ = s;
        return s;
      }
    }
    /**
     * <code>optional string colour = 5;</code>
     */
    public com.google.protobuf.ByteString
        getColourBytes() {
      java.lang.Object ref = colour_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        colour_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getServerIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, serverId_);
      }
      if (!getDiscordChannelIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, discordChannelId_);
      }
      if (!getCommandBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, command_);
      }
      if (!getCommandOutputBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, commandOutput_);
      }
      if (!getColourBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, colour_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getServerIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, serverId_);
      }
      if (!getDiscordChannelIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, discordChannelId_);
      }
      if (!getCommandBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, command_);
      }
      if (!getCommandOutputBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, commandOutput_);
      }
      if (!getColourBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, colour_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof club.moddedminecraft.polychat.core.messagelibrary.CommandProtos.GenericCommandResult)) {
        return super.equals(obj);
      }
      club.moddedminecraft.polychat.core.messagelibrary.CommandProtos.GenericCommandResult other = (club.moddedminecraft.polychat.core.messagelibrary.CommandProtos.GenericCommandResult) obj;

      boolean result = true;
      result = result && getServerId()
          .equals(other.getServerId());
      result = result && getDiscordChannelId()
          .equals(other.getDiscordChannelId());
      result = result && getCommand()
          .equals(other.getCommand());
      result = result && getCommandOutput()
          .equals(other.getCommandOutput());
      result = result && getColour()
          .equals(other.getColour());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + SERVERID_FIELD_NUMBER;
      hash = (53 * hash) + getServerId().hashCode();
      hash = (37 * hash) + DISCORDCHANNELID_FIELD_NUMBER;
      hash = (53 * hash) + getDiscordChannelId().hashCode();
      hash = (37 * hash) + COMMAND_FIELD_NUMBER;
      hash = (53 * hash) + getCommand().hashCode();
      hash = (37 * hash) + COMMANDOUTPUT_FIELD_NUMBER;
      hash = (53 * hash) + getCommandOutput().hashCode();
      hash = (37 * hash) + COLOUR_FIELD_NUMBER;
      hash = (53 * hash) + getColour().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static club.moddedminecraft.polychat.core.messagelibrary.CommandProtos.GenericCommandResult parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static club.moddedminecraft.polychat.core.messagelibrary.CommandProtos.GenericCommandResult parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static club.moddedminecraft.polychat.core.messagelibrary.CommandProtos.GenericCommandResult parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static club.moddedminecraft.polychat.core.messagelibrary.CommandProtos.GenericCommandResult parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static club.moddedminecraft.polychat.core.messagelibrary.CommandProtos.GenericCommandResult parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static club.moddedminecraft.polychat.core.messagelibrary.CommandProtos.GenericCommandResult parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static club.moddedminecraft.polychat.core.messagelibrary.CommandProtos.GenericCommandResult parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static club.moddedminecraft.polychat.core.messagelibrary.CommandProtos.GenericCommandResult parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static club.moddedminecraft.polychat.core.messagelibrary.CommandProtos.GenericCommandResult parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static club.moddedminecraft.polychat.core.messagelibrary.CommandProtos.GenericCommandResult parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(club.moddedminecraft.polychat.core.messagelibrary.CommandProtos.GenericCommandResult prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code polychat.GenericCommandResult}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:polychat.GenericCommandResult)
        club.moddedminecraft.polychat.core.messagelibrary.CommandProtos.GenericCommandResultOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return club.moddedminecraft.polychat.core.messagelibrary.CommandProtos.internal_static_polychat_GenericCommandResult_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return club.moddedminecraft.polychat.core.messagelibrary.CommandProtos.internal_static_polychat_GenericCommandResult_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                club.moddedminecraft.polychat.core.messagelibrary.CommandProtos.GenericCommandResult.class, club.moddedminecraft.polychat.core.messagelibrary.CommandProtos.GenericCommandResult.Builder.class);
      }

      // Construct using club.moddedminecraft.polychat.core.messagelibrary.CommandProtos.GenericCommandResult.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        serverId_ = "";

        discordChannelId_ = "";

        command_ = "";

        commandOutput_ = "";

        colour_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return club.moddedminecraft.polychat.core.messagelibrary.CommandProtos.internal_static_polychat_GenericCommandResult_descriptor;
      }

      public club.moddedminecraft.polychat.core.messagelibrary.CommandProtos.GenericCommandResult getDefaultInstanceForType() {
        return club.moddedminecraft.polychat.core.messagelibrary.CommandProtos.GenericCommandResult.getDefaultInstance();
      }

      public club.moddedminecraft.polychat.core.messagelibrary.CommandProtos.GenericCommandResult build() {
        club.moddedminecraft.polychat.core.messagelibrary.CommandProtos.GenericCommandResult result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public club.moddedminecraft.polychat.core.messagelibrary.CommandProtos.GenericCommandResult buildPartial() {
        club.moddedminecraft.polychat.core.messagelibrary.CommandProtos.GenericCommandResult result = new club.moddedminecraft.polychat.core.messagelibrary.CommandProtos.GenericCommandResult(this);
        result.serverId_ = serverId_;
        result.discordChannelId_ = discordChannelId_;
        result.command_ = command_;
        result.commandOutput_ = commandOutput_;
        result.colour_ = colour_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof club.moddedminecraft.polychat.core.messagelibrary.CommandProtos.GenericCommandResult) {
          return mergeFrom((club.moddedminecraft.polychat.core.messagelibrary.CommandProtos.GenericCommandResult)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(club.moddedminecraft.polychat.core.messagelibrary.CommandProtos.GenericCommandResult other) {
        if (other == club.moddedminecraft.polychat.core.messagelibrary.CommandProtos.GenericCommandResult.getDefaultInstance()) return this;
        if (!other.getServerId().isEmpty()) {
          serverId_ = other.serverId_;
          onChanged();
        }
        if (!other.getDiscordChannelId().isEmpty()) {
          discordChannelId_ = other.discordChannelId_;
          onChanged();
        }
        if (!other.getCommand().isEmpty()) {
          command_ = other.command_;
          onChanged();
        }
        if (!other.getCommandOutput().isEmpty()) {
          commandOutput_ = other.commandOutput_;
          onChanged();
        }
        if (!other.getColour().isEmpty()) {
          colour_ = other.colour_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        club.moddedminecraft.polychat.core.messagelibrary.CommandProtos.GenericCommandResult parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (club.moddedminecraft.polychat.core.messagelibrary.CommandProtos.GenericCommandResult) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object serverId_ = "";
      /**
       * <code>optional string serverId = 1;</code>
       */
      public java.lang.String getServerId() {
        java.lang.Object ref = serverId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          serverId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string serverId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getServerIdBytes() {
        java.lang.Object ref = serverId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          serverId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string serverId = 1;</code>
       */
      public Builder setServerId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        serverId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string serverId = 1;</code>
       */
      public Builder clearServerId() {
        
        serverId_ = getDefaultInstance().getServerId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string serverId = 1;</code>
       */
      public Builder setServerIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        serverId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object discordChannelId_ = "";
      /**
       * <code>optional string discordChannelId = 2;</code>
       */
      public java.lang.String getDiscordChannelId() {
        java.lang.Object ref = discordChannelId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          discordChannelId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string discordChannelId = 2;</code>
       */
      public com.google.protobuf.ByteString
          getDiscordChannelIdBytes() {
        java.lang.Object ref = discordChannelId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          discordChannelId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string discordChannelId = 2;</code>
       */
      public Builder setDiscordChannelId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        discordChannelId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string discordChannelId = 2;</code>
       */
      public Builder clearDiscordChannelId() {
        
        discordChannelId_ = getDefaultInstance().getDiscordChannelId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string discordChannelId = 2;</code>
       */
      public Builder setDiscordChannelIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        discordChannelId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object command_ = "";
      /**
       * <code>optional string command = 3;</code>
       */
      public java.lang.String getCommand() {
        java.lang.Object ref = command_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          command_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string command = 3;</code>
       */
      public com.google.protobuf.ByteString
          getCommandBytes() {
        java.lang.Object ref = command_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          command_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string command = 3;</code>
       */
      public Builder setCommand(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        command_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string command = 3;</code>
       */
      public Builder clearCommand() {
        
        command_ = getDefaultInstance().getCommand();
        onChanged();
        return this;
      }
      /**
       * <code>optional string command = 3;</code>
       */
      public Builder setCommandBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        command_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object commandOutput_ = "";
      /**
       * <code>optional string commandOutput = 4;</code>
       */
      public java.lang.String getCommandOutput() {
        java.lang.Object ref = commandOutput_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          commandOutput_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string commandOutput = 4;</code>
       */
      public com.google.protobuf.ByteString
          getCommandOutputBytes() {
        java.lang.Object ref = commandOutput_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          commandOutput_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string commandOutput = 4;</code>
       */
      public Builder setCommandOutput(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        commandOutput_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string commandOutput = 4;</code>
       */
      public Builder clearCommandOutput() {
        
        commandOutput_ = getDefaultInstance().getCommandOutput();
        onChanged();
        return this;
      }
      /**
       * <code>optional string commandOutput = 4;</code>
       */
      public Builder setCommandOutputBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        commandOutput_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object colour_ = "";
      /**
       * <code>optional string colour = 5;</code>
       */
      public java.lang.String getColour() {
        java.lang.Object ref = colour_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          colour_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string colour = 5;</code>
       */
      public com.google.protobuf.ByteString
          getColourBytes() {
        java.lang.Object ref = colour_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          colour_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string colour = 5;</code>
       */
      public Builder setColour(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        colour_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string colour = 5;</code>
       */
      public Builder clearColour() {
        
        colour_ = getDefaultInstance().getColour();
        onChanged();
        return this;
      }
      /**
       * <code>optional string colour = 5;</code>
       */
      public Builder setColourBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        colour_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:polychat.GenericCommandResult)
    }

    // @@protoc_insertion_point(class_scope:polychat.GenericCommandResult)
    private static final club.moddedminecraft.polychat.core.messagelibrary.CommandProtos.GenericCommandResult DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new club.moddedminecraft.polychat.core.messagelibrary.CommandProtos.GenericCommandResult();
    }

    public static club.moddedminecraft.polychat.core.messagelibrary.CommandProtos.GenericCommandResult getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GenericCommandResult>
        PARSER = new com.google.protobuf.AbstractParser<GenericCommandResult>() {
      public GenericCommandResult parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new GenericCommandResult(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GenericCommandResult> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GenericCommandResult> getParserForType() {
      return PARSER;
    }

    public club.moddedminecraft.polychat.core.messagelibrary.CommandProtos.GenericCommandResult getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PromoteMemberCommandOrBuilder extends
      // @@protoc_insertion_point(interface_extends:polychat.PromoteMemberCommand)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string serverId = 1;</code>
     */
    java.lang.String getServerId();
    /**
     * <code>optional string serverId = 1;</code>
     */
    com.google.protobuf.ByteString
        getServerIdBytes();

    /**
     * <code>optional string username = 2;</code>
     */
    java.lang.String getUsername();
    /**
     * <code>optional string username = 2;</code>
     */
    com.google.protobuf.ByteString
        getUsernameBytes();
  }
  /**
   * Protobuf type {@code polychat.PromoteMemberCommand}
   */
  public  static final class PromoteMemberCommand extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:polychat.PromoteMemberCommand)
      PromoteMemberCommandOrBuilder {
    // Use PromoteMemberCommand.newBuilder() to construct.
    private PromoteMemberCommand(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PromoteMemberCommand() {
      serverId_ = "";
      username_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private PromoteMemberCommand(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              serverId_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              username_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return club.moddedminecraft.polychat.core.messagelibrary.CommandProtos.internal_static_polychat_PromoteMemberCommand_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return club.moddedminecraft.polychat.core.messagelibrary.CommandProtos.internal_static_polychat_PromoteMemberCommand_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              club.moddedminecraft.polychat.core.messagelibrary.CommandProtos.PromoteMemberCommand.class, club.moddedminecraft.polychat.core.messagelibrary.CommandProtos.PromoteMemberCommand.Builder.class);
    }

    public static final int SERVERID_FIELD_NUMBER = 1;
    private volatile java.lang.Object serverId_;
    /**
     * <code>optional string serverId = 1;</code>
     */
    public java.lang.String getServerId() {
      java.lang.Object ref = serverId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        serverId_ = s;
        return s;
      }
    }
    /**
     * <code>optional string serverId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getServerIdBytes() {
      java.lang.Object ref = serverId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        serverId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USERNAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object username_;
    /**
     * <code>optional string username = 2;</code>
     */
    public java.lang.String getUsername() {
      java.lang.Object ref = username_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        username_ = s;
        return s;
      }
    }
    /**
     * <code>optional string username = 2;</code>
     */
    public com.google.protobuf.ByteString
        getUsernameBytes() {
      java.lang.Object ref = username_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        username_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getServerIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, serverId_);
      }
      if (!getUsernameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, username_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getServerIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, serverId_);
      }
      if (!getUsernameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, username_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof club.moddedminecraft.polychat.core.messagelibrary.CommandProtos.PromoteMemberCommand)) {
        return super.equals(obj);
      }
      club.moddedminecraft.polychat.core.messagelibrary.CommandProtos.PromoteMemberCommand other = (club.moddedminecraft.polychat.core.messagelibrary.CommandProtos.PromoteMemberCommand) obj;

      boolean result = true;
      result = result && getServerId()
          .equals(other.getServerId());
      result = result && getUsername()
          .equals(other.getUsername());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + SERVERID_FIELD_NUMBER;
      hash = (53 * hash) + getServerId().hashCode();
      hash = (37 * hash) + USERNAME_FIELD_NUMBER;
      hash = (53 * hash) + getUsername().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static club.moddedminecraft.polychat.core.messagelibrary.CommandProtos.PromoteMemberCommand parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static club.moddedminecraft.polychat.core.messagelibrary.CommandProtos.PromoteMemberCommand parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static club.moddedminecraft.polychat.core.messagelibrary.CommandProtos.PromoteMemberCommand parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static club.moddedminecraft.polychat.core.messagelibrary.CommandProtos.PromoteMemberCommand parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static club.moddedminecraft.polychat.core.messagelibrary.CommandProtos.PromoteMemberCommand parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static club.moddedminecraft.polychat.core.messagelibrary.CommandProtos.PromoteMemberCommand parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static club.moddedminecraft.polychat.core.messagelibrary.CommandProtos.PromoteMemberCommand parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static club.moddedminecraft.polychat.core.messagelibrary.CommandProtos.PromoteMemberCommand parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static club.moddedminecraft.polychat.core.messagelibrary.CommandProtos.PromoteMemberCommand parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static club.moddedminecraft.polychat.core.messagelibrary.CommandProtos.PromoteMemberCommand parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(club.moddedminecraft.polychat.core.messagelibrary.CommandProtos.PromoteMemberCommand prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code polychat.PromoteMemberCommand}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:polychat.PromoteMemberCommand)
        club.moddedminecraft.polychat.core.messagelibrary.CommandProtos.PromoteMemberCommandOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return club.moddedminecraft.polychat.core.messagelibrary.CommandProtos.internal_static_polychat_PromoteMemberCommand_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return club.moddedminecraft.polychat.core.messagelibrary.CommandProtos.internal_static_polychat_PromoteMemberCommand_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                club.moddedminecraft.polychat.core.messagelibrary.CommandProtos.PromoteMemberCommand.class, club.moddedminecraft.polychat.core.messagelibrary.CommandProtos.PromoteMemberCommand.Builder.class);
      }

      // Construct using club.moddedminecraft.polychat.core.messagelibrary.CommandProtos.PromoteMemberCommand.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        serverId_ = "";

        username_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return club.moddedminecraft.polychat.core.messagelibrary.CommandProtos.internal_static_polychat_PromoteMemberCommand_descriptor;
      }

      public club.moddedminecraft.polychat.core.messagelibrary.CommandProtos.PromoteMemberCommand getDefaultInstanceForType() {
        return club.moddedminecraft.polychat.core.messagelibrary.CommandProtos.PromoteMemberCommand.getDefaultInstance();
      }

      public club.moddedminecraft.polychat.core.messagelibrary.CommandProtos.PromoteMemberCommand build() {
        club.moddedminecraft.polychat.core.messagelibrary.CommandProtos.PromoteMemberCommand result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public club.moddedminecraft.polychat.core.messagelibrary.CommandProtos.PromoteMemberCommand buildPartial() {
        club.moddedminecraft.polychat.core.messagelibrary.CommandProtos.PromoteMemberCommand result = new club.moddedminecraft.polychat.core.messagelibrary.CommandProtos.PromoteMemberCommand(this);
        result.serverId_ = serverId_;
        result.username_ = username_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof club.moddedminecraft.polychat.core.messagelibrary.CommandProtos.PromoteMemberCommand) {
          return mergeFrom((club.moddedminecraft.polychat.core.messagelibrary.CommandProtos.PromoteMemberCommand)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(club.moddedminecraft.polychat.core.messagelibrary.CommandProtos.PromoteMemberCommand other) {
        if (other == club.moddedminecraft.polychat.core.messagelibrary.CommandProtos.PromoteMemberCommand.getDefaultInstance()) return this;
        if (!other.getServerId().isEmpty()) {
          serverId_ = other.serverId_;
          onChanged();
        }
        if (!other.getUsername().isEmpty()) {
          username_ = other.username_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        club.moddedminecraft.polychat.core.messagelibrary.CommandProtos.PromoteMemberCommand parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (club.moddedminecraft.polychat.core.messagelibrary.CommandProtos.PromoteMemberCommand) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object serverId_ = "";
      /**
       * <code>optional string serverId = 1;</code>
       */
      public java.lang.String getServerId() {
        java.lang.Object ref = serverId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          serverId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string serverId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getServerIdBytes() {
        java.lang.Object ref = serverId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          serverId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string serverId = 1;</code>
       */
      public Builder setServerId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        serverId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string serverId = 1;</code>
       */
      public Builder clearServerId() {
        
        serverId_ = getDefaultInstance().getServerId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string serverId = 1;</code>
       */
      public Builder setServerIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        serverId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object username_ = "";
      /**
       * <code>optional string username = 2;</code>
       */
      public java.lang.String getUsername() {
        java.lang.Object ref = username_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          username_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string username = 2;</code>
       */
      public com.google.protobuf.ByteString
          getUsernameBytes() {
        java.lang.Object ref = username_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          username_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string username = 2;</code>
       */
      public Builder setUsername(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        username_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string username = 2;</code>
       */
      public Builder clearUsername() {
        
        username_ = getDefaultInstance().getUsername();
        onChanged();
        return this;
      }
      /**
       * <code>optional string username = 2;</code>
       */
      public Builder setUsernameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        username_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:polychat.PromoteMemberCommand)
    }

    // @@protoc_insertion_point(class_scope:polychat.PromoteMemberCommand)
    private static final club.moddedminecraft.polychat.core.messagelibrary.CommandProtos.PromoteMemberCommand DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new club.moddedminecraft.polychat.core.messagelibrary.CommandProtos.PromoteMemberCommand();
    }

    public static club.moddedminecraft.polychat.core.messagelibrary.CommandProtos.PromoteMemberCommand getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PromoteMemberCommand>
        PARSER = new com.google.protobuf.AbstractParser<PromoteMemberCommand>() {
      public PromoteMemberCommand parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new PromoteMemberCommand(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PromoteMemberCommand> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PromoteMemberCommand> getParserForType() {
      return PARSER;
    }

    public club.moddedminecraft.polychat.core.messagelibrary.CommandProtos.PromoteMemberCommand getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_polychat_GenericCommand_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_polychat_GenericCommand_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_polychat_GenericCommandResult_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_polychat_GenericCommandResult_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_polychat_PromoteMemberCommand_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_polychat_PromoteMemberCommand_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016commands.proto\022\010polychat\"l\n\016GenericCom" +
      "mand\022\030\n\020discordChannelId\030\001 \001(\t\022\032\n\022discor" +
      "dCommandName\030\002 \001(\t\022\026\n\016defaultCommand\030\003 \001" +
      "(\t\022\014\n\004args\030\004 \001(\t\"z\n\024GenericCommandResult" +
      "\022\020\n\010serverId\030\001 \001(\t\022\030\n\020discordChannelId\030\002" +
      " \001(\t\022\017\n\007command\030\003 \001(\t\022\025\n\rcommandOutput\030\004" +
      " \001(\t\022\016\n\006colour\030\005 \001(\t\":\n\024PromoteMemberCom" +
      "mand\022\020\n\010serverId\030\001 \001(\t\022\020\n\010username\030\002 \001(\t" +
      "BB\n1club.moddedminecraft.polychat.core.m" +
      "essagelibraryB\rCommandProtosb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_polychat_GenericCommand_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_polychat_GenericCommand_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_polychat_GenericCommand_descriptor,
        new java.lang.String[] { "DiscordChannelId", "DiscordCommandName", "DefaultCommand", "Args", });
    internal_static_polychat_GenericCommandResult_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_polychat_GenericCommandResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_polychat_GenericCommandResult_descriptor,
        new java.lang.String[] { "ServerId", "DiscordChannelId", "Command", "CommandOutput", "Colour", });
    internal_static_polychat_PromoteMemberCommand_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_polychat_PromoteMemberCommand_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_polychat_PromoteMemberCommand_descriptor,
        new java.lang.String[] { "ServerId", "Username", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
